apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpong-app-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong-app # This is the app as declared in the deployment.
  ports:
    - port: 3457 # This is a port that is available to the cluster, in this case it can be ~ anything
      protocol: TCP
      targetPort: 3001 # This is the target port