apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 1024Mi
    limits.cpu: "1500m"
    limits.memory: 2048Mi
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: exercises-quota
  namespace: exercises
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 1024Mi
    limits.cpu: "1500m"
    limits.memory: 2048Mi
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: the-project-prod-quota
  namespace: the-project-prod
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 1024Mi
    limits.cpu: "1500m"
    limits.memory: 2048Mi
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: the-project-staging-quota
  namespace: the-project-staging
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 1024Mi
    limits.cpu: "1500m"
    limits.memory: 2048Mi
    persistentvolumeclaims: "5"

