apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
spec:
  storageClassName: image-pv-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/image
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim
spec:
  volumeName: todo-app-pv
  storageClassName: image-pv-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
