apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  serviceName: todo-app-svc
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app-writer
          image: PROJECT/todo-app-writer
          imagePullPolicy: Always
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/image
          envFrom:
          - configMapRef:
              name: todo-config
        - name: todo-app
          image: PROJECT/todo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/image
          envFrom:
            - configMapRef:
                name: todo-config
  volumeClaimTemplates:
    - metadata:
        name: image-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000